In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('../data/house_prices_india.csv')
df.head(3)

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810145,42491,5,2.50,3650,9050,2.0,0,4,5,...,1921,0,122003,52.8645,-114.557,2880,5400,2,58,2380000
1,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
2,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000

In [5]:
df.columns

Index(['id', 'Date', 'number of bedrooms', 'number of bathrooms',
       'living area', 'lot area', 'number of floors', 'waterfront present',
       'number of views', 'condition of the house', 'grade of the house',
       'Area of the house(excluding basement)', 'Area of the basement',
       'Built Year', 'Renovation Year', 'Postal Code', 'Lattitude',
       'Longitude', 'living_area_renov', 'lot_area_renov',
       'Number of schools nearby', 'Distance from the airport', 'Price'],
      dtype='str')

Fix Missing Data, Formats

In [6]:
# Fix Missing Data, Formats
data = {
    "A": [1, 2, None, 4],
    "B": ["2021-01-01", "2021-02-01", "2021-03-01", None],
    "c": ["10", "20", "30", "40"]
}
sample_df = pd.DataFrame(data)
sample_df

     A           B   c
0  1.0  2021-01-01  10
1  2.0  2021-02-01  20
2  NaN  2021-03-01  30
3  4.0         NaN  40

In [7]:
sample_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      float64
 1   B       3 non-null      str
 2   c       4 non-null      str
dtypes: float64(1), str(2)
memory usage: 228.0 bytes

Eiter yoither fill the missing data or drop the rows/columns with missing data. Also, convert the data types to appropriate formats.

In [8]:
sample_df1 = sample_df.copy()
sample_df1.dropna(inplace=True)
sample_df1

     A           B   c
0  1.0  2021-01-01  10
1  2.0  2021-02-01  20

In [9]:
sample_df2 = sample_df.copy()
sample_df2.fillna({
    "A": sample_df2["A"].mean(),
    "B": pd.to_datetime(sample_df2["B"].fillna("2021-01-01")),
    "c": sample_df2["c"].fillna("0")
}, inplace=True)
sample_df2

          A                    B   c
0  1.000000           2021-01-01  10
1  2.000000           2021-02-01  20
2  2.333333           2021-03-01  30
3  4.000000  2021-01-01 00:00:00  40

In [10]:
sample_df2['c'] = sample_df2['c'].astype(int)
sample_df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      float64
 1   B       4 non-null      object
 2   c       4 non-null      int64
dtypes: float64(1), int64(1), object(1)
memory usage: 228.0+ bytes